version: '3.8'
services:
  quotesbackend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app/backend
  quotesfrontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "4201:4200"
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules